### ISSUE TITLE
非常感谢你的付出，可否同时更新txt和m3u源？

### ISSUE THREAD

**Issue by laozhu999** [LiuYi0526/IPTV#4]
因为ios好像没有txt播放器。谢谢啦

**Comment by LiuYi0526** [comment]
可以的，但是我精力有限，尽量做到哈

**Comment by LiuYi0526** [comment]
当前的m3u应该也是可以正常使用的呀

**Comment by laozhu999** [comment]
是的，m3u可以使用。只是发现比txt少了一些台。我强迫症犯了，哈哈哈。这已经是我看到的最好的源信息了，真心感谢你的付出。那就有时间再说吧。
