### ISSUE TITLE
CCTV源

### ISSUE THREAD

**Issue by Gelishuai** [LiuYi0526/IPTV#7]
您好，CCTV5+无法打开了。能不能添加上 CCTV 16的直播源？

**Comment by LiuYi0526** [comment]
您好：
CCTV5+源2可正常播放，现已删除不可用直播源；
CCTV16直播源在CCTV5+的下方，包含高清及4K版本，之前已经存在

**Comment by ycylyqy** [comment]
你好，cctv16 4k的是不能打开了吗
